version: "3.9"
#FROM python:3.11-slim

services:
  web:
    build: .
    image: services:hunghung
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  celery_worker:
    build: .
    image: celery:hunghung
    container_name: celery_worker
    command: celery -A celery_config worker --loglevel=info --pool=solo
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"